Fix slow performance with S3 #662 #301 #508
jazzband/sorl-thumbnail pull request #719
Opened 2023-01-24 12:32 UTC by krukas

2023-02-10 09:40 UTC, khink commented
This would be nice to have.

2023-08-07 09:06 UTC, krukas commented
What do I need to do to get this merged? @uri-rodberg @JanMalte

2023-08-12 18:24 UTC, claudep requested changes

2023-08-12 18:24 UTC, claudep commented on sorl/thumbnail/images.py
> +
What about using https://docs.python.org/3/library/functools.html#functools.lru_cache instead?

2023-08-14 08:32 UTC, krukas commented on sorl/thumbnail/images.py
> +
Thanks for the suggestion, I have updated it to use `lru_cache`

2023-08-15 06:45 UTC, claudep approved these changes
Thanks, looks good now!

2023-08-15 06:45 UTC, merged