fixed DeprecationWarning
jazzband/sorl-thumbnail pull request #737
Opened 2023-07-24 13:08 UTC by LarryMartell

fixed DeprecationWarning

2023-07-24 13:10 UTC, claudep commented
As I commented in the previous PR, Python 3.7 is EOL, so it should be removed from the test matrix. The the `install-requires` will not be needed any more.

2023-07-24 15:17 UTC, LarryMartell commented
So are you saying the issue is closed and this PR is not needed any more?

2023-07-24 15:19 UTC, claudep commented
No, it's not. However, if 3.7 support is dropped, this will simplify this patch, as the try/except will not be necessary.

2023-07-24 17:10 UTC, LarryMartell commented
I have a PR our to fix the tests in master. Shall I remove the 3.7 support in that branch?

2023-07-24 21:50 UTC, claudep requested changes
Thanks, you are on the right track!

2023-07-24 21:50 UTC, claudep commented on .github/workflows/test.yml
> +        name: Python ${{ matrix.python-version }}
This change is not useful, please revert.

2023-07-24 21:50 UTC, claudep commented on setup.py
> +    python_requires='>=3.8',
You can also remove the 3.7 classifier below.

2023-07-24 21:50 UTC, claudep commented on sorl/__init__.py
> +except Exception:
Is there a reason to catch exceptions here? Did you read somewhere that it was needed?

2023-07-24 22:44 UTC, LarryMartell commented on .github/workflows/test.yml
> +        name: Python ${{ matrix.python-version }}
Done

2023-07-24 22:44 UTC, LarryMartell commented on setup.py
> +    python_requires='>=3.8',
Done

2023-07-24 22:44 UTC, LarryMartell commented on sorl/__init__.py
> +except Exception:
No, was just being defensive. I've removed it.

2023-07-24 23:43 UTC, LarryMartell commented
After making these small changes the tests are failing in my forked branch, but it's not clear why.

https://github.com/LarryMartell/sorl-thumbnail/actions/runs/5650549930/job/15307090121#step:10:458

2023-07-25 00:36 UTC, uri-rodberg commented
@claudep This PR looks fine to me now. Do you still require changes or is it OK with you now? And why are the tests canceled and failing? I expected the tests to pass now.

2023-07-25 03:37 UTC, LarryMartell commented
The tests were passing until I made some very small changes Claude
requested. It’s not clear to me at all why they’re failing now.

On Mon, Jul 24, 2023 at 5:36 PM אורי ***@***.***> wrote:

> @claudep <https://github.com/claudep> This PR looks fine to me now. Do
> you still require changes or is it OK with you now? And why are the tests
> canceled and failing? I expected the tests to pass now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jazzband/sorl-thumbnail/pull/737#issuecomment-1648800216>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7MIFNAXQL6CYCWH2NIALXR4IIRANCNFSM6AAAAAA2VR6BWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-25 05:20 UTC, LarryMartell commented
The tests are very persnickety. The presence or absence of a blank line
seems to make them pass or fail.

On Mon, Jul 24, 2023 at 8:37 PM Larry Martell ***@***.***>
wrote:

> The tests were passing until I made some very small changes Claude
> requested. It’s not clear to me at all why they’re failing now.
>
> On Mon, Jul 24, 2023 at 5:36 PM אורי ***@***.***> wrote:
>
>> @claudep <https://github.com/claudep> This PR looks fine to me now. Do
>> you still require changes or is it OK with you now? And why are the tests
>> canceled and failing? I expected the tests to pass now.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jazzband/sorl-thumbnail/pull/737#issuecomment-1648800216>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAJ7MIFNAXQL6CYCWH2NIALXR4IIRANCNFSM6AAAAAA2VR6BWQ>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-07-25 05:40 UTC, uri-rodberg commented
> The tests are very persnickety. The presence or absence of a blank line seems to make them pass or fail. On Mon, Jul 24, 2023 at 8:37 PM Larry Martell ***@***.***> wrote:
> […](#)
> The tests were passing until I made some very small changes Claude requested. It’s not clear to me at all why they’re failing now.

@LarryMartell Can you please add a blank line at the end of `.github/workflows/test.yml`, and a blank line at the end of `sorl/__init__.py`, and then we will check if the tests pass?

2023-07-25 07:16 UTC, claudep commented
I created #738 to only make the Python 3.7 drop (and let Larry as author), so we can then concentrate on the `version` issue only.

2023-07-25 07:47 UTC, claudep commented
According to https://pypi.org/project/setuptools-scm/#retrieving-package-version-at-runtime, we should still catch `PackageNotFoundError` for cases where the package is not installed (typically during tests or dev).

2023-07-25 14:18 UTC, LarryMartell commented
test.yml already had a blank line. Added one to __init__.py, tests still
failing.

‪On Mon, Jul 24, 2023 at 10:40 PM ‫אורי‬‎ ***@***.***> wrote:‬

> The tests are very persnickety. The presence or absence of a blank line
> seems to make them pass or fail. On Mon, Jul 24, 2023 at 8:37 PM Larry
> Martell *@*.***> wrote:
> … <#m_-5043465268867401432_>
> The tests were passing until I made some very small changes Claude
> requested. It’s not clear to me at all why they’re failing now.
>
> @LarryMartell <https://github.com/LarryMartell> Can you please add a
> blank line at the end of .github/workflows/test.yml, and a blank line at
> the end of sorl/__init__.py, and then we will check if the tests pass?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jazzband/sorl-thumbnail/pull/737#issuecomment-1649156053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7MICU2CHH75GCZKHO6ZTXR5L4XANCNFSM6AAAAAA2VR6BWQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-25 14:19 UTC, claudep commented
Blank lines have nothing to do with the failure. Please read my comment above.

2023-07-25 14:23 UTC, LarryMartell commented
Here is the error from the test:

sorl/__init__.py:8:1: W391 blank line at end of file

Which comment? About PackageNotFound? I added that.

On Tue, Jul 25, 2023 at 7:19 AM Claude Paroz ***@***.***> wrote:
>
> Blank lines have nothing to do with the failure. Please read my comment above.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-07-25 14:29 UTC, claudep commented
Looks good. Try now to rebase on master, the only changed file should be `sorl/__init__.py`.

2023-07-25 14:33 UTC, LarryMartell commented
Removed blank line, tests are passing now.

On Tue, Jul 25, 2023 at 7:30 AM Claude Paroz ***@***.***>
wrote:

> Looks good. Try now to rebase on master, the only changed file should be
> sorl/__init__.py.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jazzband/sorl-thumbnail/pull/737#issuecomment-1649955573>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7MIFGD3EWYDAIHFM52RLXR7J6HANCNFSM6AAAAAA2VR6BWQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-25 15:28 UTC, uri-rodberg commented
@LarryMartell Do you know how to rebase? This PR should be rebased on branch master. It looks to me it's still not rebased. Please read about rebasing and rebase all your commits on branch master.

2023-07-25 16:18 UTC, LarryMartell commented
Yes, I know how to rebase. My 727.1 branch has been rebased with master.

2023-07-25 16:58 UTC, LarryMartell commented
I have a fork and from github I sync my fork's master with the upstream, so
it should be the same. But in any case I followed your exact directions and
rebased.

The 5 files shown as modified have indeed all been modified in my branch.


‪On Tue, Jul 25, 2023 at 9:44 AM ‫אורי‬‎ ***@***.***> wrote:‬

> Yes, I know how to rebase. My 727.1 branch has been rebased with master.
>
> @LarryMartell <https://github.com/LarryMartell> You rebased origin/master
> and not upstream/master. Please run the following commands:
>
> git remote add upstream https://github.com/jazzband/sorl-thumbnail.git
>
> git remote -v
>
> The results should be:
>
> origin  https://github.com/LarryMartell/sorl-thumbnail.git (fetch)
> origin  https://github.com/LarryMartell/sorl-thumbnail.git (push)
> upstream        https://github.com/jazzband/sorl-thumbnail.git (fetch)
> upstream        https://github.com/jazzband/sorl-thumbnail.git (push)
>
> git fetch upstream
>
> git rebase upstream/master
>
> Remember that any time when we ask you to rebase branch master, we mean
> upstream/master and not origin/master. But it's a good practice to have
> origin/master always point to the same commit as upstream/master.
>
> The results should be 2 files changed from upstream/master, one of them
> only with one blank line. Currently the PR shows me 5 files changed. If it
> doesn't change, please close this PR and create a new one, because maybe
> the PR doesn't take into account changes to branch master made after you
> created this PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jazzband/sorl-thumbnail/pull/737#issuecomment-1650183286>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7MIB7BVXYDIR2NGJNLI3XR7ZWFANCNFSM6AAAAAA2VR6BWQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-25 18:59 UTC, LarryMartell commented
There are 2 things in this branch - fixing the deprecation warning and
removing python 3.7.

On Tue, Jul 25, 2023 at 9:57 AM Larry Martell ***@***.***>
wrote:

> I have a fork and from github I sync my fork's master with the upstream,
> so it should be the same. But in any case I followed your exact directions
> and rebased.
>
> The 5 files shown as modified have indeed all been modified in my branch.
>
>
> ‪On Tue, Jul 25, 2023 at 9:44 AM ‫אורי‬‎ ***@***.***>
> wrote:‬
>
>> Yes, I know how to rebase. My 727.1 branch has been rebased with master.
>>
>> @LarryMartell <https://github.com/LarryMartell> You rebased
>> origin/master and not upstream/master. Please run the following commands:
>>
>> git remote add upstream https://github.com/jazzband/sorl-thumbnail.git
>>
>> git remote -v
>>
>> The results should be:
>>
>> origin  https://github.com/LarryMartell/sorl-thumbnail.git (fetch)
>> origin  https://github.com/LarryMartell/sorl-thumbnail.git (push)
>> upstream        https://github.com/jazzband/sorl-thumbnail.git (fetch)
>> upstream        https://github.com/jazzband/sorl-thumbnail.git (push)
>>
>> git fetch upstream
>>
>> git rebase upstream/master
>>
>> Remember that any time when we ask you to rebase branch master, we mean
>> upstream/master and not origin/master. But it's a good practice to have
>> origin/master always point to the same commit as upstream/master.
>>
>> The results should be 2 files changed from upstream/master, one of them
>> only with one blank line. Currently the PR shows me 5 files changed. If it
>> doesn't change, please close this PR and create a new one, because maybe
>> the PR doesn't take into account changes to branch master made after you
>> created this PR.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jazzband/sorl-thumbnail/pull/737#issuecomment-1650183286>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAJ7MIB7BVXYDIR2NGJNLI3XR7ZWFANCNFSM6AAAAAA2VR6BWQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-07-31 03:14 UTC, LarryMartell commented
Are there any issues with this PR that are preventing it from being accepted and merged?

2023-07-31 03:50 UTC, uri-rodberg commented
@LarryMartell Please contact me by email. Your mailbox is full.

2023-07-31 19:16 UTC, JanMalte approved these changes

2023-08-01 00:40 UTC, uri-rodberg commented
I'm going to create another PR instead of this PR. Closing this PR.

2023-08-01 00:40 UTC, closed without merging